# Generated by Django 5.0 on 2023-12-17 15:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Vendor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(max_length=255)),
                (
                    "order_data",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 12, 17, 15, 21, 3, 890275)
                    ),
                ),
                ("delivery_date", models.DateTimeField()),
                ("items", models.JSONField(default=list)),
                ("quantity", models.IntegerField()),
                ("status", models.CharField(default="pending", max_length=255)),
                ("quality_rating", models.FloatField(null=True)),
                (
                    "issue_date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 12, 17, 15, 21, 3, 890383)
                    ),
                ),
                ("acknowledgment_date", models.DateTimeField(null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Vendor.vendorprofile",
                    ),
                ),
            ],
        ),
    ]
