# Generated by Django 5.0 on 2023-12-17 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("POTracking", "0002_remove_purchaseorder_order_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 17, 15, 24, 49, 455706, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 17, 15, 24, 49, 455616, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
